package cn.springmvc.model;

public class SysRoleAction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_action.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_action.role_id
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_action.action_id
     *
     * @mbggenerated
     */
    private Integer actionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_action.id
     *
     * @return the value of sys_role_action.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_action.id
     *
     * @param id the value for sys_role_action.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_action.role_id
     *
     * @return the value of sys_role_action.role_id
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_action.role_id
     *
     * @param roleId the value for sys_role_action.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_action.action_id
     *
     * @return the value of sys_role_action.action_id
     *
     * @mbggenerated
     */
    public Integer getActionId() {
        return actionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_action.action_id
     *
     * @param actionId the value for sys_role_action.action_id
     *
     * @mbggenerated
     */
    public void setActionId(Integer actionId) {
        this.actionId = actionId;
    }
}